### ISSUE TITLE
Fails to bootup on Mac OS X

### ISSUE THREAD

**Issue by DamienOReilly** [slavaz/embedded-postgresql-maven-plugin#8]
Hitting a null pointer after the extraction is done:

<pre>Extract /Users/user/.embedpostgresql/postgresql-9.5.7-1-osx-binaries.zip START
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Extract /Users/user/.embedpostgresql/postgresql-9.5.7-1-osx-binaries.zip DONE
Exception in thread "postgres-embedded" java.lang.RuntimeException: Invocation of method startPostgres threw exception
	at com.github.slavaz.maven.plugin.postgresql.embedded.psql.IsolatedPgInstanceManager.invokeStaticMethod(IsolatedPgInstanceManager.java:80)
	at com.github.slavaz.maven.plugin.postgresql.embedded.psql.IsolatedPgInstanceManager.lambda$start$0(IsolatedPgInstanceManager.java:28)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.github.slavaz.maven.plugin.postgresql.embedded.psql.IsolatedPgInstanceManager.invokeStaticMethod(IsolatedPgInstanceManager.java:76)
	... 2 more
Caused by: java.lang.NullPointerException
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1012)
	at de.flapdoodle.embed.process.runtime.ProcessControl.start(ProcessControl.java:205)
	at de.flapdoodle.embed.process.runtime.AbstractProcess.<init>(AbstractProcess.java:98)
	at ru.yandex.qatools.embed.postgresql.AbstractPGProcess.<init>(AbstractPGProcess.java:19)
	at ru.yandex.qatools.embed.postgresql.PostgresProcess.<init>(PostgresProcess.java:68)
	at ru.yandex.qatools.embed.postgresql.PostgresExecutable.start(PostgresExecutable.java:25)
	at ru.yandex.qatools.embed.postgresql.PostgresExecutable.start(PostgresExecutable.java:13)
	at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
	at com.github.slavaz.maven.plugin.postgresql.embedded.psql.PgInstanceManager.start(PgInstanceManager.java:30)
	at com.github.slavaz.maven.plugin.postgresql.embedded.psql.IsolatedPgInstanceManager.startPostgres(IsolatedPgInstanceManager.java:49)
	... 7 more</pre>

**Comment by slavaz** [comment]
I need steps to reproduce.

Would you please share values for: pgServerVersion, pgHost, pgPort, dbName, userName, password, pgDatabaseDir, pgLocale, pgCharset?

**Comment by DamienOReilly** [comment]
Sure thing, I haven't specified all properties. I just worked of the README example.

<pre>
                            <pgServerVersion>9.5</pgServerVersion>
                            <pgServerPort>5432</pgServerPort>
                            <dbName>postgres</dbName>
                            <userName>test</userName>
                            <password>test</password>
</pre>

**Comment by jasonfagan** [comment]
I had a look into this and  the cause is a missing `pgHost` configuration, if this is not set then the `java.lang.ProcessBuilder::start `method will throw a NPE as one of the arguments is null.

The solution for now is to add `pgHost` like so

`
 <pgServerVersion>9.5</pgServerVersion>
 <pgServerPort>5432</pgServerPort>
 <pgHost>localhost</pgHost>
 <dbName>postgres</dbName>
 <userName>test</userName>
 <password>test</password>
`

Having the plugin default to localhost would be a good fix for the long run.

**Comment by slavaz** [comment]
I've created the branch: https://github.com/slavaz/embedded-postgresql-maven-plugin/pull/9
Are you able to check it?

**Comment by jasonfagan** [comment]
Tested without `pgHost` set and all works fine. Thanks for fixing so quickly.

**Comment by slavaz** [comment]
Released new version 1.2.3:
[INFO] Uploaded: https://oss.sonatype.org:443/service/local/staging/deployByRepositoryId/comgithubslavaz-1008/com/github/slavaz/embedded-postgresql-maven-plugin/1.2.2/embedded-postgresql-maven-plugin-1.2.2-javadoc.jar 

Just wait above a day - need to update all Maven mirrors...
